image: "gitlab.parp.gov.pl:5055/ci/ssfz:latest"

stages:
    - build
    - tests
    - security
    - standards
    - stats
    - doc
    - postbuild
  
build:
    stage: build
    allow_failure: true
    script:
        - /usr/bin/composer.phar global show -i > .gitlab-ci/composer.dump
        - php -d memory_limit=5G /usr/bin/composer.phar install --no-dev --prefer-dist --no-suggest --no-progress --no-interaction --no-scripts
    artifacts:
        expire_in: 1 day
        untracked: true
    only:
        - merge_requests

parallellint:
    stage: tests
    allow_failure: false
    script:
        - /root/.composer/vendor/bin/parallel-lint --colors --blame --exclude vendor .
    only:
        - merge_requests

yamllint:
    stage: tests
    allow_failure: false
    script:
        - /root/.composer/vendor/bin/yaml-lint --format txt src/
        - /root/.composer/vendor/bin/yaml-lint --format txt app/
    only:
        - merge_requests

psr12:
    stage: standards
    allow_failure: false
    script:
        - /root/.composer/vendor/bin/phpcs -n --colors --report=full --standard=PSR12 --extensions=php src/
        - /root/.composer/vendor/bin/phpcs -n --colors --report=full --standard=PSR12 --extensions=php
          --ignore="AppKernel.php, AppCache.php, AsseticScriptHandler.php, SymfonyRequirements.php"
          app/
    only:
        - merge_requests

linelength:
    stage: standards
    allow_failure: true
    script:
        - /root/.composer/vendor/bin/phpcs --config-set encoding utf-8
        - /root/.composer/vendor/bin/phpcs -n --colors --report=full --standard="./.gitlab-ci/phpcs_line_length.xml" --extensions=php src/
    only:
        - merge_requests

eofeol:
    stage: standards
    allow_failure: true
    script:
        - /root/.composer/vendor/bin/phpcs --config-set encoding utf-8
        - /root/.composer/vendor/bin/phpcs -n --colors --report=full --standard="./.gitlab-ci/phpcs_eof.xml" --extensions=php src/
    only:
        - merge_requests

twigcs:
    stage: standards
    allow_failure: false
    script:
        - /root/.composer/vendor/bin/twigcs lint src/
    only:
        - merge_requests

phpmd:
    stage: standards
    allow_failure: false
    script:
        - /root/.composer/vendor/bin/phpmd src/ text ".gitlab-ci/phpmd.xml"
    only:
        - merge_requests

phpdoc:
    stage: standards
    allow_failure: false
    script:
        - /root/.composer/vendor/bin/phpdoccheck --directory="src/"
    only:
        - merge_requests

phpcpd:
    stage: stats
    allow_failure: true
    script:
        - sed -i 's/memory_limit = 128M/memory_limit = 1G/g' /etc/php7/php.ini
        - /root/.composer/vendor/bin/phpcpd --min-lines=10 --min-tokens=100 --verbose --exclude="tests/" src/
    only:
        - merge_requests

phploc:
    stage: stats
    allow_failure: false
    script:
        - /root/.composer/vendor/bin/phploc src/
    only:
        - merge_requests

sami:
    stage: doc
    allow_failure: false
    script:
        - mkdir -p doc/api
        - php -d memory_limit=1G /usr/bin/sami.phar update "./.gitlab-ci/sami.conf" -v
    artifacts:
        untracked: false
        expire_in: 1 day
        paths:
            - .gitlab-ci/phpdoc
    only:
        - merge_requests

automerge:
    stage: postbuild
    allow_failure: false
    script:
        - echo "machine gitlab.parp.gov.pl login ci_automerge password $pass" > ~/.netrc
        - chmod 600  ~/.netrc
        - git config --global user.name "Merging Bot"
        - git config --global user.email "linuxadmin@parp.gov.pl"
        - mkdir automerge && cd automerge
        - git clone -b master https://gitlab.parp.gov.pl/parp/ssfz
        - cd lsi
        - git checkout development
        - git merge --no-ff -m "Auto merge by gitlabci job" master
        - git push origin development
    only:
        - merge_requests
    except:
        variables:
            - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master"
    when: on_success
