imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@SsfzBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: pl

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
    fragments: ~
    http_method_override: true
    #translator: { fallbacks: [pl] }

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_3_layout.html.twig', 'bootstrap_3_horizontal_layout.html.twig']

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.root_dir%/data/data.db3'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    port: '%mailer_port%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    encryption: '%mailer_encryption%'
    stream_options:
      ssl:
        allow_self_signed: true
        verify_peer: false
#    spool: { type: memory }

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~

waldo_datatable:
    all:    ~
    js:    
        language : 
            are_you_sure: Jesteś pewny ?
            you_need_to_select_at_least_one_element: Musisz wybrać co najmniej jeden element.
            #search: Szukaj
            execute: "Wykonać"
            ok: "OK"
            searchPlaceholder: ""
            emptyTable:     "Brak danych"
            info:           "Pozycje od _START_ do _END_ z _TOTAL_ łącznie"
            infoEmpty:      "Pozycji 0 z 0 dostępnych"
            infoFiltered:   "(filtrowanie spośród _MAX_ dostępnych pozycji)"
            infoPostFix:    ""
            infoThousands:  " "
            lengthMenu:     "Pokaż _MENU_ pozycji"
            loadingRecords: "Wczytywanie..."
            processing:     "Przetwarzanie..."
            search:         "Szukaj:"
            zeroRecords:    "Nie znaleziono pasujących pozycji"
            paginate:
                first:    "Pierwsza"
                last:     "Ostatnia"
                next:     "Następna"
                previous: "Poprzednia"
            aria:
                sortAscending:  ": aktywuj, by posortować kolumnę rosnąco"
                sortDescending: ": aktywuj, by posortować kolumnę malejąco"

doctrine_migrations:
    dir_name: "%kernel.root_dir%/../setup/migrations"
    namespace: 'Application\Migrations'
    table_name: 'migration_versions'
    name: 'Application Migrations'
