# https://symfony.com/doc/current/service_container.html
parameters:

services:
    ldap:
        class: Symfony\Component\Ldap\LdapClient
        arguments:
            ["@=container.getparameter('ldap')['host']", "@=container.getparameter('ldap')['port']", "%ldap_version%", "%ldap_ssl%", "%ldap_tls%"]

    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        public:    false
        arguments:
            - 'mysql:host=%database_host%;port=%database_port%;dbname=%database_name%'
            - { db_table: sessions, db_username: '%database_user%', db_password: '%database_password%' }
