# https://symfony.com/doc/current/service_container.html
parameters:

services:
    ldap:
        class: Symfony\Component\Ldap\LdapClient
        arguments:
            ["@=container.getparameter('ldap')['host']", "@=container.getparameter('ldap')['port']", "%ldap_version%", "%ldap_ssl%", "%ldap_tls%"]
