<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Migracja 20190701134658.
 */
class Version20190701134658 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE sfz_dane_poreczen
            ADD liczba_por_wyplaconych_mikro_przeds INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych dla mikro przedsiębiorstw.\',
            ADD liczba_por_wyplaconych_czesciowo_splaconych_mikro_przeds INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i częściowo spłaconych dla mikro przedsiębiorstw.\',
            ADD liczba_por_wyplaconych_calkowicie_splaconych_mikro_przeds INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i całkowicie spłaconych dla mikro przedsiębiorstw.\',
            ADD liczba_por_wyplaconych_nieodzyskanych_mikro_przeds INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i nieodzyskanych dla mikro przedsiębiorstw.\',
            ADD liczba_por_wyplaconych_male_przeds INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych dla małych przedsiębiorstw.\',
            ADD liczba_por_wyplaconych_czesciowo_splaconych_male_przeds INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i częściowo spłaconych dla małych przedsiębiorstw.\',
            ADD liczba_por_wyplaconych_calkowicie_splaconych_male_przeds INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i całkowicie spłaconych dla małych przedsiębiorstw.\',
            ADD liczba_por_wyplaconych_nieodzyskanych_male_przeds INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i nieodzyskanych dla małych przedsiębiorstw.\',
            ADD liczba_por_wyplaconych_srednie_przeds INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych dla średnich przedsiębiorstw.\',
            ADD liczba_por_wyplaconych_czesciowo_splaconych_srednie_przeds INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i częściowo spłaconych dla średnich przedsiębiorstw.\',
            ADD liczba_por_wyplaconych_calkowicie_splaconych_srednie_przeds INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i całkowicie spłaconych dla średnich przedsiębiorstw.\',
            ADD liczba_por_wyplaconych_nieodzyskanych_srednie_przeds INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i nieodzyskanych dla średnich przedsiębiorstw.\',
            ADD liczba_por_wyplaconych_na_kredyt_obrotowy INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych na kredyt obrotowy.\',
            ADD liczba_por_wyplaconych_czesciowo_splaconych_na_kredyt_obrotowy INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i częściowo spłaconych na kredyt obrotowy.\',
            ADD liczba_por_wyplaconych_calkowicie_splaconych_na_kredyt_obrotowy INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i całkowicie spłaconych na kredyt obrotowy.\',
            ADD liczba_por_wyplaconych_nieodzyskanych_na_kredyt_obrotowy INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i nieodzyskanych na kredyt obrotowy.\',
            ADD liczba_por_wyplaconych_na_kredyt_inwest INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych na kredyt inwestycyjny.\',
            ADD liczba_por_wyplaconych_czesciowo_splaconych_na_kredyt_inwest INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i częściowo spłaconych na kredyt inwestycyjny.\',
            ADD liczba_por_wyplaconych_calkowicie_splaconych_na_kredyt_inwest INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i całkowicie spłaconych na kredyt inwestycyjny.\',
            ADD liczba_por_wyplaconych_nieodzyskanych_na_kredyt_inwest INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i nieodzyskanych na kredyt inwestycyjny.\',
            ADD liczba_por_wyplaconych_na_pozyczke_obrot INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych na pożyczkę obrotową.\',
            ADD liczba_por_wyplaconych_czesciowo_splaconych_na_pozyczke_obrot INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i częściowo spłaconych na pożyczkę obrotową.\',
            ADD liczba_por_wyplaconych_calkowicie_splaconych_na_pozyczke_obrot INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i całkowicie spłaconych na pożyczkę obrotową.\',
            ADD liczba_por_wyplaconych_nieodzyskanych_na_pozyczke_obrot INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i nieodzyskanych na pożyczkę obrotową.\',
            ADD liczba_por_wyplaconych_na_pozyczke_inwest INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych na pożyczkę inwestycyjną.\',
            ADD liczba_por_wyplaconych_czesciowo_splaconych_na_pozyczke_inwest INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i częściowo spłaconych na pożyczkę inwestycyjną.\',
            ADD liczba_por_wyplaconych_calkowicie_splaconych_na_pozyczke_inwest INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i całkowicie spłaconych na pożyczkę inwestycyjną.\',
            ADD liczba_por_wyplaconych_nieodzyskanych_na_pozyczke_inwest INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i nieodzyskanych na pożyczkę inwestycyjną.\',
            ADD liczba_por_pozostalych_wyplaconych INT DEFAULT 0 NOT NULL COMMENT \'Liczba pozostałych poręczeń wypłaconych.\',
            ADD liczba_por_pozostalych_wyplaconych_czesciowo_splaconych INT DEFAULT 0 NOT NULL COMMENT \'Liczba pozostałych poręczeń wypłaconych i częściowo spłaconych.\',
            ADD liczba_por_pozostalych_wyplaconych_calkowicie_splaconych INT DEFAULT 0 NOT NULL COMMENT \'Liczba pozostałych poręczeń wypłaconych i całkowicie spłaconych.\',
            ADD liczba_por_pozostalych_wyplaconych_nieodzyskanych INT DEFAULT 0 NOT NULL COMMENT \'Liczba pozostałych poręczeń wypłaconych i nieodzyskanych.\',
            ADD liczba_wadiow_por_pozostalych_wyplaconych INT DEFAULT 0 NOT NULL COMMENT \'Liczba wadiów pozostałych poręczeń wypłaconych.\',
            ADD liczba_wadiow_por_pozostalych_wyplaconych_czesciowo_splaconych INT DEFAULT 0 NOT NULL COMMENT \'Liczba wadiów pozostałych poręczeń wypłaconych i częściowo spłaconych.\',
            ADD liczba_wadiow_por_pozostalych_wyplaconych_calkowicie_splaconych INT DEFAULT 0 NOT NULL COMMENT \'Liczba wadiów pozostałych poręczeń wypłaconych i całkowicie spłaconych.\',
            ADD liczba_wadiow_por_pozostalych_wyplaconych_nieodzyskanych INT DEFAULT 0 NOT NULL COMMENT \'Liczba wadiów pozostałych poręczeń wypłaconych i nieodzyskanych.\',
            ADD liczba_por_wyplaconych_dzial_produkcyjne INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych na działania produkcyjne.\',
            ADD liczba_por_wyplaconych_czesciowo_splaconych_dzial_produkcyjne INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i częściowo spłaconych na działania produkcyjne.\',
            ADD liczba_por_wyplaconych_calkowicie_splaconych_dzial_produkcyjne INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i całkowicie spłaconych na działania produkcyjne.\',
            ADD liczba_por_wyplaconych_nieodzyskanych_dzial_produkcyjne INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i nieodzyskanych na działania produkcyjne.\',
            ADD liczba_por_wyplaconych_dzial_handlowe INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych na działania handlowe.\',
            ADD liczba_por_wyplaconych_czesciowo_splaconych_dzial_handlowe INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i częściowo spłaconych na działania handlowe.\',
            ADD liczba_por_wyplaconych_calkowicie_splaconych_dzial_handlowe INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i całkowicie spłaconych na działania handlowe.\',
            ADD liczba_por_wyplaconych_nieodzyskanych_dzial_handlowe INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i nieodzyskanych na działania handlowe.\',
            ADD liczba_por_wyplaconych_dzial_uslugowe INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych na działania usługowe.\',
            ADD liczba_por_wyplaconych_czesciowo_splaconych_dzial_uslugowe INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i częściowo spłaconych na działania usługowe.\',
            ADD liczba_por_wyplaconych_calkowicie_splaconych_dzial_uslugowe INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i całkowicie spłaconych na działania usługowe.\',
            ADD liczba_por_wyplaconych_nieodzyskanych_dzial_uslugowe INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i nieodzyskanych na działania usługowe.\',
            ADD liczba_por_wyplaconych_dzial_budownicze INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych na działania budownicze.\',
            ADD liczba_por_wyplaconych_czesciowo_splaconych_dzial_budownicze INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i częściowo spłaconych na działania budownicze.\',
            ADD liczba_por_wyplaconych_calkowicie_splaconych_dzial_budownicze INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i całkowicie spłaconych na działania budownicze.\',
            ADD liczba_por_wyplaconych_nieodzyskanych_dzial_budownicze INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i nieodzyskanych na działania budownicze.\',
            ADD liczba_por_wyplaconych_dzial_inne INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych na działania inne.\',
            ADD liczba_por_wyplaconych_czesciowo_splaconych_dzial_inne INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i częściowo spłaconych na działania inne.\',
            ADD liczba_por_wyplaconych_calkowicie_splaconych_dzial_inne INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i całkowicie spłaconych na działania inne.\',
            ADD liczba_por_wyplaconych_nieodzyskanych_dzial_inne INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i nieodzyskanych na działania inne.\',
            ADD liczba_por_wyplaconych_dla_bankow INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych dla banków.\',
            ADD liczba_por_wyplaconych_czesciowo_splaconych_dla_bankow INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i częściowo spłaconych dla banków.\',
            ADD liczba_por_wyplaconych_calkowicie_splaconych_dla_bankow INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i całkowicie spłaconych dla banków.\',
            ADD liczba_por_wyplaconych_nieodzyskanych_dla_bankow INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i nieodzyskanych dla banków.\',
            ADD liczba_por_wyplaconych_dla_fund_pozyczk INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych dla funduszy pożyczkowych\',
            ADD liczba_por_wyplaconych_czesciowo_splaconych_dla_fund_pozyczk INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i częściowo spłaconych dla funduszy pożyczkowych.\',
            ADD liczba_por_wyplaconych_calkowicie_splaconych_dla_fund_pozyczk INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i całkowicie spłaconych dla funduszy pożyczkowych.\',
            ADD liczba_por_wyplaconych_nieodzyskanych_dla_fund_pozyczk INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i nieodzyskanych dla funduszy pożyczkowych.\',
            ADD liczba_por_wyplaconych_dla_innych_podm INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych dla innych podmiotów\',
            ADD liczba_por_wyplaconych_czesciowo_splaconych_dla_innych_podm INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i częściowo spłaconych dla innych podmiotów.\',
            ADD liczba_por_wyplaconych_calkowicie_splaconych_dla_innych_podm INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i całkowicie spłaconych dla innych podmiotów.\',
            ADD liczba_por_wyplaconych_nieodzyskanych_dla_innych_podm INT DEFAULT 0 NOT NULL COMMENT \'Liczba poręczeń wypłaconych i nieodzyskanych dla innych podmiotów\',
            ADD kwota_por_wyplaconych_mikro_przeds NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych dla mikro przedsiębiorstw.\',
            ADD kwota_por_wyplaconych_czesciowo_splaconych_mikro_przeds NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i częściowo spłaconych dla mikro przedsiębiorstw.\',
            ADD kwota_por_wyplaconych_calkowicie_splaconych_mikro_przeds NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i całkowicie spłaconych dla mikro przedsiębiorstw.\',
            ADD kwota_por_wyplaconych_nieodzyskanych_mikro_przeds NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i nieodzyskanych dla mikro przedsiębiorstw.\',
            ADD kwota_por_wyplaconych_male_przeds NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych dla małych przedsiębiorstw.\',
            ADD kwota_por_wyplaconych_czesciowo_splaconych_male_przeds NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i częściowo spłaconych dla małych przedsiębiorstw.\',
            ADD kwota_por_wyplaconych_calkowicie_splaconych_male_przeds NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i całkowicie spłaconych dla małych przedsiębiorstw.\',
            ADD kwota_por_wyplaconych_nieodzyskanych_male_przeds NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i nieodzyskanych dla małych przedsiębiorstw.\',
            ADD kwota_por_wyplaconych_srednie_przeds NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych dla średnich przedsiębiorstw.\',
            ADD kwota_por_wyplaconych_czesciowo_splaconych_srednie_przeds NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i częściowo spłaconych dla średnich przedsiębiorstw.\',
            ADD kwota_por_wyplaconych_calkowicie_splaconych_srednie_przeds NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i całkowicie spłaconych dla średnich przedsiębiorstw.\',
            ADD kwota_por_wyplaconych_nieodzyskanych_srednie_przeds NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i nieodzyskanych dla średnich przedsiębiorstw.\',
            ADD kwota_por_wyplaconych_na_kredyt_obrotowy NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych na kredyt obrotowy.\',
            ADD kwota_por_wyplaconych_czesciowo_splaconych_na_kredyt_obrotowy NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i częściowo spłaconych na kredyt obrotowy.\',
            ADD kwota_por_wyplaconych_calkowicie_splaconych_na_kredyt_obrotowy NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i całkowicie spłaconych na kredyt obrotowy.\',
            ADD kwota_por_wyplaconych_nieodzyskanych_na_kredyt_obrotowy NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i nieodzyskanych na kredyt obrotowy.\',
            ADD kwota_por_wyplaconych_na_kredyt_inwest NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych na kredyt inwestycyjny.\',
            ADD kwota_por_wyplaconych_czesciowo_splaconych_na_kredyt_inwest NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i częściowo spłaconych na kredyt inwestycyjny.\',
            ADD kwota_por_wyplaconych_calkowicie_splaconych_na_kredyt_inwest NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i całkowicie spłaconych na kredyt inwestycyjny.\',
            ADD kwota_por_wyplaconych_nieodzyskanych_na_kredyt_inwest NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i nieodzyskanych na kredyt inwestycyjny.\',
            ADD kwota_por_wyplaconych_na_pozyczke_obrot NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych na pożyczkę obrotową.\',
            ADD kwota_por_wyplaconych_czesciowo_splaconych_na_pozyczke_obrot NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i częściowo spłaconych na pożyczkę obrotową.\',
            ADD kwota_por_wyplaconych_calkowicie_splaconych_na_pozyczke_obrot NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i całkowicie spłaconych na pożyczkę obrotową.\',
            ADD kwota_por_wyplaconych_nieodzyskanych_na_pozyczke_obrot NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i nieodzyskanych na pożyczkę obrotową.\',
            ADD kwota_por_wyplaconych_na_pozyczke_inwest NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych na pożyczkę inwestycyjną.\',
            ADD kwota_por_wyplaconych_czesciowo_splaconych_na_pozyczke_inwest NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i częściowo spłaconych na pożyczkę inwestycyjną.\',
            ADD kwota_por_wyplaconych_calkowicie_splaconych_na_pozyczke_inwest NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i całkowicie spłaconych na pożyczkę inwestycyjną.\',
            ADD kwota_por_wyplaconych_nieodzyskanych_na_pozyczke_inwest NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i nieodzyskanych na pożyczkę inwestycyjną.\',
            ADD kwota_por_pozostalych_wyplaconych NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Liczba pozostałych poręczeń wypłaconych.\',
            ADD kwota_por_pozostalych_wyplaconych_czesciowo_splaconych NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Liczba pozostałych poręczeń wypłaconych i częściowo spłaconych.\',
            ADD kwota_por_pozostalych_wyplaconych_calkowicie_splaconych NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Liczba pozostałych poręczeń wypłaconych i całkowicie spłaconych.\',
            ADD kwota_por_pozostalych_wyplaconych_nieodzyskanych NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Liczba pozostałych poręczeń wypłaconych i nieodzyskanych.\',
            ADD kwota_wadiow_por_pozostalych_wyplaconych NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Liczba wadiów pozostałych poręczeń wypłaconych.\',
            ADD kwota_wadiow_por_pozostalych_wyplaconych_czesciowo_splaconych NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Liczba wadiów pozostałych poręczeń wypłaconych i częściowo spłaconych.\',
            ADD kwota_wadiow_por_pozostalych_wyplaconych_calkowicie_splaconych NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Liczba wadiów pozostałych poręczeń wypłaconych i całkowicie spłaconych.\',
            ADD kwota_wadiow_por_pozostalych_wyplaconych_nieodzyskanych NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Liczba wadiów pozostałych poręczeń wypłaconych i nieodzyskanych.\',
            ADD kwota_por_wyplaconych_dzial_produkcyjne NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych na działania produkcyjne.\',
            ADD kwota_por_wyplaconych_czesciowo_splaconych_dzial_produkcyjne NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i częściowo spłaconych na działania produkcyjne.\',
            ADD kwota_por_wyplaconych_calkowicie_splaconych_dzial_produkcyjne NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i całkowicie spłaconych na działania produkcyjne.\',
            ADD kwota_por_wyplaconych_nieodzyskanych_dzial_produkcyjne NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i nieodzyskanych na działania produkcyjne.\',
            ADD kwota_por_wyplaconych_dzial_handlowe NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych na działania handlowe.\',
            ADD kwota_por_wyplaconych_czesciowo_splaconych_dzial_handlowe NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i częściowo spłaconych na działania handlowe.\',ADD kwota_por_wyplaconych_calkowicie_splaconych_dzial_handlowe NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i całkowicie spłaconych na działania handlowe.\',
            ADD kwota_por_wyplaconych_nieodzyskanych_dzial_handlowe NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i nieodzyskanych na działania handlowe.\',
            ADD kwota_por_wyplaconych_dzial_uslugowe NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych na działania usługowe.\',
            ADD kwota_por_wyplaconych_czesciowo_splaconych_dzial_uslugowe NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i częściowo spłaconych na działania usługowe.\',ADD kwota_por_wyplaconych_calkowicie_splaconych_dzial_uslugowe NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i całkowicie spłaconych na działania usługowe.\',
            ADD kwota_por_wyplaconych_nieodzyskanych_dzial_uslugowe NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i nieodzyskanych na działania usługowe.\',
            ADD kwota_por_wyplaconych_dzial_budownicze NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych na działania budownicze.\',
            ADD kwota_por_wyplaconych_czesciowo_splaconych_dzial_budownicze NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i częściowo spłaconych na działania budownicze.\',
            ADD kwota_por_wyplaconych_calkowicie_splaconych_dzial_budownicze NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i całkowicie spłaconych na działania budownicze.\',
            ADD kwota_por_wyplaconych_nieodzyskanych_dzial_budownicze NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i nieodzyskanych na działania budownicze.\',
            ADD kwota_por_wyplaconych_dzial_inne NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych na działania inne.\',
            ADD kwota_por_wyplaconych_czesciowo_splaconych_dzial_inne NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i częściowo spłaconych na działania inne.\',
            ADD kwota_por_wyplaconych_calkowicie_splaconych_dzial_inne NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i całkowicie spłaconych na działania inne.\',
            ADD kwota_por_wyplaconych_nieodzyskanych_dzial_inne NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i nieodzyskanych na działania inne.\',
            ADD kwota_por_wyplaconych_dla_bankow NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych dla banków.\',
            ADD kwota_por_wyplaconych_czesciowo_splaconych_dla_bankow NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i częściowo spłaconych dla banków.\',
            ADD kwota_por_wyplaconych_calkowicie_splaconych_dla_bankow NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i całkowicie spłaconych dla banków.\',
            ADD kwota_por_wyplaconych_nieodzyskanych_dla_bankow NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i nieodzyskanych dla banków.\',
            ADD kwota_por_wyplaconych_dla_fund_pozyczk NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych dla funduszy pożyczkowych\',
            ADD kwota_por_wyplaconych_czesciowo_splaconych_dla_fund_pozyczk NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i częściowo spłaconych dla funduszy pożyczkowych.\',
            ADD kwota_por_wyplaconych_calkowicie_splaconych_dla_fund_pozyczk NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i całkowicie spłaconych dla funduszy pożyczkowych.\',
            ADD kwota_por_wyplaconych_nieodzyskanych_dla_fund_pozyczk NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i nieodzyskanych dla funduszy pożyczkowych.\',
            ADD kwota_por_wyplaconych_dla_innych_podm NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych dla innych podmiotów\',
            ADD kwota_por_wyplaconych_czesciowo_splaconych_dla_innych_podm NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i częściowo spłaconych dla innych podmiotów.\',
            ADD kwota_por_wyplaconych_calkowicie_splaconych_dla_innych_podm NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i całkowicie spłaconych dla innych podmiotów.\',
            ADD kwota_por_wyplaconych_nieodzyskanych_dla_innych_podm NUMERIC(11, 2) DEFAULT \'0\' NOT NULL COMMENT \'Kwota poręczeń wypłaconych i nieodzyskanych dla innych podmiotów\'');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {

        $this->abortIf(true, 'Not supported.');

        /*
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE sfz_dane_poreczen
            DROP liczba_por_wyplaconych_mikro_przeds,
            DROP liczba_por_wyplaconych_czesciowo_splaconych_mikro_przeds,
            DROP liczba_por_wyplaconych_calkowicie_splaconych_mikro_przeds,
            DROP liczba_por_wyplaconych_nieodzyskanych_mikro_przeds,
            DROP liczba_por_wyplaconych_male_przeds,
            DROP liczba_por_wyplaconych_czesciowo_splaconych_male_przeds,
            DROP liczba_por_wyplaconych_calkowicie_splaconych_male_przeds,
            DROP liczba_por_wyplaconych_nieodzyskanych_male_przeds,
            DROP liczba_por_wyplaconych_srednie_przeds,
            DROP liczba_por_wyplaconych_czesciowo_splaconych_srednie_przeds,
            DROP liczba_por_wyplaconych_calkowicie_splaconych_srednie_przeds,
            DROP liczba_por_wyplaconych_nieodzyskanych_srednie_przeds,
            DROP liczba_por_wyplaconych_na_kredyt_obrotowy,
            DROP liczba_por_wyplaconych_czesciowo_splaconych_na_kredyt_obrotowy,
            DROP liczba_por_wyplaconych_calkowicie_splaconych_na_kredyt_obrotowy,
            DROP liczba_por_wyplaconych_nieodzyskanych_na_kredyt_obrotowy,
            DROP liczba_por_wyplaconych_na_kredyt_inwest,
            DROP liczba_por_wyplaconych_czesciowo_splaconych_na_kredyt_inwest,
            DROP liczba_por_wyplaconych_calkowicie_splaconych_na_kredyt_inwest,
            DROP liczba_por_wyplaconych_nieodzyskanych_na_kredyt_inwest,
            DROP liczba_por_wyplaconych_na_pozyczke_obrot,
            DROP liczba_por_wyplaconych_czesciowo_splaconych_na_pozyczke_obrot,
            DROP liczba_por_wyplaconych_calkowicie_splaconych_na_pozyczke_obrot,
            DROP liczba_por_wyplaconych_nieodzyskanych_na_pozyczke_obrot,
            DROP liczba_por_wyplaconych_na_pozyczke_inwest,
            DROP liczba_por_wyplaconych_czesciowo_splaconych_na_pozyczke_inwest,
            DROP liczba_por_wyplaconych_calkowicie_splaconych_na_pozyczke_inwest,
            DROP liczba_por_wyplaconych_nieodzyskanych_na_pozyczke_inwest,
            DROP liczba_por_pozostalych_wyplaconych,
            DROP liczba_por_pozostalych_wyplaconych_czesciowo_splaconych,
            DROP liczba_por_pozostalych_wyplaconych_calkowicie_splaconych,
            DROP liczba_por_pozostalych_wyplaconych_nieodzyskanych,
            DROP liczba_wadiow_por_pozostalych_wyplaconych,
            DROP liczba_wadiow_por_pozostalych_wyplaconych_czesciowo_splaconych,
            DROP liczba_wadiow_por_pozostalych_wyplaconych_calkowicie_splaconych,
            DROP liczba_wadiow_por_pozostalych_wyplaconych_nieodzyskanych,
            DROP liczba_por_wyplaconych_dzial_produkcyjne,
            DROP liczba_por_wyplaconych_czesciowo_splaconych_dzial_produkcyjne,
            DROP liczba_por_wyplaconych_calkowicie_splaconych_dzial_produkcyjne,
            DROP liczba_por_wyplaconych_nieodzyskanych_dzial_produkcyjne,
            DROP liczba_por_wyplaconych_dzial_handlowe,
            DROP liczba_por_wyplaconych_czesciowo_splaconych_dzial_handlowe,
            DROP liczba_por_wyplaconych_calkowicie_splaconych_dzial_handlowe,
            DROP liczba_por_wyplaconych_nieodzyskanych_dzial_handlowe,
            DROP liczba_por_wyplaconych_dzial_uslugowe,
            DROP liczba_por_wyplaconych_czesciowo_splaconych_dzial_uslugowe,
            DROP liczba_por_wyplaconych_calkowicie_splaconych_dzial_uslugowe,
            DROP liczba_por_wyplaconych_nieodzyskanych_dzial_uslugowe,
            DROP liczba_por_wyplaconych_dzial_budownicze,
            DROP liczba_por_wyplaconych_czesciowo_splaconych_dzial_budownicze,
            DROP liczba_por_wyplaconych_calkowicie_splaconych_dzial_budownicze,
            DROP liczba_por_wyplaconych_nieodzyskanych_dzial_budownicze,
            DROP liczba_por_wyplaconych_dzial_inne,
            DROP liczba_por_wyplaconych_czesciowo_splaconych_dzial_inne,
            DROP liczba_por_wyplaconych_calkowicie_splaconych_dzial_inne,
            DROP liczba_por_wyplaconych_nieodzyskanych_dzial_inne,
            DROP liczba_por_wyplaconych_dla_bankow,
            DROP liczba_por_wyplaconych_czesciowo_splaconych_dla_bankow,
            DROP liczba_por_wyplaconych_calkowicie_splaconych_dla_bankow,
            DROP liczba_por_wyplaconych_nieodzyskanych_dla_bankow,
            DROP liczba_por_wyplaconych_dla_fund_pozyczk,
            DROP liczba_por_wyplaconych_czesciowo_splaconych_dla_fund_pozyczk,
            DROP liczba_por_wyplaconych_calkowicie_splaconych_dla_fund_pozyczk,
            DROP liczba_por_wyplaconych_nieodzyskanych_dla_fund_pozyczk,
            DROP liczba_por_wyplaconych_dla_innych_podm,
            DROP liczba_por_wyplaconych_czesciowo_splaconych_dla_innych_podm,
            DROP liczba_por_wyplaconych_calkowicie_splaconych_dla_innych_podm,
            DROP liczba_por_wyplaconych_nieodzyskanych_dla_innych_podm,
            DROP kwota_por_wyplaconych_mikro_przeds,
            DROP kwota_por_wyplaconych_czesciowo_splaconych_mikro_przeds,
            DROP kwota_por_wyplaconych_calkowicie_splaconych_mikro_przeds,
            DROP kwota_por_wyplaconych_nieodzyskanych_mikro_przeds,
            DROP kwota_por_wyplaconych_male_przeds,
            DROP kwota_por_wyplaconych_czesciowo_splaconych_male_przeds,
            DROP kwota_por_wyplaconych_calkowicie_splaconych_male_przeds,
            DROP kwota_por_wyplaconych_nieodzyskanych_male_przeds,
            DROP kwota_por_wyplaconych_srednie_przeds,
            DROP kwota_por_wyplaconych_czesciowo_splaconych_srednie_przeds,
            DROP kwota_por_wyplaconych_calkowicie_splaconych_srednie_przeds,
            DROP kwota_por_wyplaconych_nieodzyskanych_srednie_przeds,
            DROP kwota_por_wyplaconych_na_kredyt_obrotowy,
            DROP kwota_por_wyplaconych_czesciowo_splaconych_na_kredyt_obrotowy,
            DROP kwota_por_wyplaconych_calkowicie_splaconych_na_kredyt_obrotowy,
            DROP kwota_por_wyplaconych_nieodzyskanych_na_kredyt_obrotowy,
            DROP kwota_por_wyplaconych_na_kredyt_inwest,
            DROP kwota_por_wyplaconych_czesciowo_splaconych_na_kredyt_inwest,
            DROP kwota_por_wyplaconych_calkowicie_splaconych_na_kredyt_inwest,
            DROP kwota_por_wyplaconych_nieodzyskanych_na_kredyt_inwest,
            DROP kwota_por_wyplaconych_na_pozyczke_obrot,
            DROP kwota_por_wyplaconych_czesciowo_splaconych_na_pozyczke_obrot,
            DROP kwota_por_wyplaconych_calkowicie_splaconych_na_pozyczke_obrot,
            DROP kwota_por_wyplaconych_nieodzyskanych_na_pozyczke_obrot,
            DROP kwota_por_wyplaconych_na_pozyczke_inwest,
            DROP kwota_por_wyplaconych_czesciowo_splaconych_na_pozyczke_inwest,
            DROP kwota_por_wyplaconych_calkowicie_splaconych_na_pozyczke_inwest,
            DROP kwota_por_wyplaconych_nieodzyskanych_na_pozyczke_inwest,
            DROP kwota_por_pozostalych_wyplaconych,
            DROP kwota_por_pozostalych_wyplaconych_czesciowo_splaconych,
            DROP kwota_por_pozostalych_wyplaconych_calkowicie_splaconych,
            DROP kwota_por_pozostalych_wyplaconych_nieodzyskanych,
            DROP kwota_wadiow_por_pozostalych_wyplaconych,
            DROP kwota_wadiow_por_pozostalych_wyplaconych_czesciowo_splaconych,
            DROP kwota_wadiow_por_pozostalych_wyplaconych_calkowicie_splaconych,
            DROP kwota_wadiow_por_pozostalych_wyplaconych_nieodzyskanych,
            DROP kwota_por_wyplaconych_dzial_produkcyjne,
            DROP kwota_por_wyplaconych_czesciowo_splaconych_dzial_produkcyjne,
            DROP kwota_por_wyplaconych_calkowicie_splaconych_dzial_produkcyjne,
            DROP kwota_por_wyplaconych_nieodzyskanych_dzial_produkcyjne,
            DROP kwota_por_wyplaconych_dzial_handlowe,
            DROP kwota_por_wyplaconych_czesciowo_splaconych_dzial_handlowe,
            DROP kwota_por_wyplaconych_calkowicie_splaconych_dzial_handlowe,
            DROP kwota_por_wyplaconych_nieodzyskanych_dzial_handlowe,
            DROP kwota_por_wyplaconych_dzial_uslugowe,
            DROP kwota_por_wyplaconych_czesciowo_splaconych_dzial_uslugowe,
            DROP kwota_por_wyplaconych_calkowicie_splaconych_dzial_uslugowe,
            DROP kwota_por_wyplaconych_nieodzyskanych_dzial_uslugowe,
            DROP kwota_por_wyplaconych_dzial_budownicze,
            DROP kwota_por_wyplaconych_czesciowo_splaconych_dzial_budownicze,
            DROP kwota_por_wyplaconych_calkowicie_splaconych_dzial_budownicze,
            DROP kwota_por_wyplaconych_nieodzyskanych_dzial_budownicze,
            DROP kwota_por_wyplaconych_dzial_inne,
            DROP kwota_por_wyplaconych_czesciowo_splaconych_dzial_inne,
            DROP kwota_por_wyplaconych_calkowicie_splaconych_dzial_inne,
            DROP kwota_por_wyplaconych_nieodzyskanych_dzial_inne,
            DROP kwota_por_wyplaconych_dla_bankow,
            DROP kwota_por_wyplaconych_czesciowo_splaconych_dla_bankow,
            DROP kwota_por_wyplaconych_calkowicie_splaconych_dla_bankow,
            DROP kwota_por_wyplaconych_nieodzyskanych_dla_bankow,
            DROP kwota_por_wyplaconych_dla_fund_pozyczk,
            DROP kwota_por_wyplaconych_czesciowo_splaconych_dla_fund_pozyczk,
            DROP kwota_por_wyplaconych_calkowicie_splaconych_dla_fund_pozyczk,
            DROP kwota_por_wyplaconych_nieodzyskanych_dla_fund_pozyczk,
            DROP kwota_por_wyplaconych_dla_innych_podm,
            DROP kwota_por_wyplaconych_czesciowo_splaconych_dla_innych_podm,
            DROP kwota_por_wyplaconych_calkowicie_splaconych_dla_innych_podm,
            DROP kwota_por_wyplaconych_nieodzyskanych_dla_innych_podm');
        */
    }
}
