<?php

namespace Parp\SsfzBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BeneficjentFormaPrawnaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BeneficjentFormaPrawnaRepository extends EntityRepository
{
}
