<?php
namespace Parp\SsfzBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RolaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolaRepository extends EntityRepository
{

    /**
     * 
     * @param string $nazwy
     * @return array
     */
    public function znajdzPoNazwach($nazwy)
    {
        return $this->createQueryBuilder('r')
                ->where('r.nazwa in (?1)')
                ->setParameter(1, $nazwy)
                ->getQuery()
                ->getResult();
    }
}
