<?php
namespace Parp\SsfzBundle\Repository;

use Parp\SsfzBundle\Entity\SpolkaHistoriaZmian;
use Doctrine\ORM\EntityRepository;

/**
 * HistoriaZmianRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriaZmianRepository extends EntityRepository
{
}
