<?php

namespace Parp\SsfzBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Parp\SsfzBundle\Entity\SpolkaHistoriaZmian;
/**
 * SpolkaHistoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpolkaHistoriaRepository extends EntityRepository
{
    /**
     * Persists spolkaHistoria
     * 
     * @param SpolkaHistoriaZmian $spolkaHistoriaZmian
     */
    public function persistSpolkaHistoriaZmian(SpolkaHistoriaZmian $spolkaHistoriaZmian)
    {
        $this->_em->persist($spolkaHistoriaZmian);        
        $this->_em->flush();
    }          
}
