<?php

namespace Parp\SsfzBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UmowaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UmowaRepository extends EntityRepository
{
}
